version: "3"
services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
  teamcity:
    image: jetbrains/teamcity-server
    ports:
      - "8112:8111"
    volumes:
      - "./data/teamcity/data_dir:/data/teamcity_server/datadir"
      - "./data/teamcity/log_dir:/opt/teamcity/logs"
  teamcity-agent:
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL=http://teamcity:8111
      - AGENT_NAME=regular_agent
  gogs:
    image: gogs/gogs
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - "./data/gogs:/data"
