version: "3"
services:
  teamcity:
    image: jetbrains/teamcity-server
    ports:
      - "8112:8111"
    volumes:
      - ./data/teamcity/data_dir:/data/teamcity_server/datadir
      - ./data/teamcity/log_dir:/opt/teamcity/logs
  teamcity-agent:
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL=http://teamcity:8111
      - AGENT_NAME=regular_agent
#  teamcity-minimal-agent:
#    image: jetbrains/teamcity-minimal-agent
#    environment:
#      - SERVER_URL=http://teamcity:8111
#      - AGENT_NAME=minimal_agent
#  bitbucket:
#    image: atlassian/bitbucket-server
#    ports:
#      - "7990:7990"
#      - "7999:7999"
#    volumes:
#      - ./data/bitbucket:/var/atlassian/application-data/bitbucket
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "443:443"
      - "80:80"
      - "22:22"
    volumes:
      - ./data/gitlab/config:/etc/gitlab
      - ./data/gitlab/logs:/var/log/gitlab
      - ./data/gitlab/data:/var/opt/gitlab
